In [2]:
words=open("names.txt",'r').read().splitlines()

In [3]:
import torch
N = torch.zeros((27,27),dtype=torch.int32)

In [4]:
import string
stoi = {c: i for i, c in enumerate(string.ascii_lowercase,start=1)}
stoi['.']=0
itos={i:s for s,i in stoi.items()}

In [5]:
for w in words:
    chs=["."]+list(w)+ ["."]
    for ch1,ch2 in zip(chs,chs[1:]):
        N[stoi[ch1],stoi[ch2]]+=1


In [6]:
g = torch.Generator()
g.manual_seed(42)

In [10]:
P= N.float()
P= P / P.sum(1,keepdims=True)
P.shape

torch.Size([27, 27])

In [13]:
for i in range(50):   
    out=[]
    idx=0
    while True:
        q= P[idx]
        idx = torch.multinomial(q, num_samples=1,replacement=True, generator=g).item()
        out.append(itos[idx])
        if idx==0:
            break
    print("".join(out))

eeeli.
adr.
rilen.
cyliklyvryoxarvabe.
e.
s.
adeden.
keyl.
ttap.
ckysuxo.
br.
shsh.
l.
miro.
b.
a.
kyigeven.
ynee.
knikeanaa.
kazy.
kelilist.
ade.
zaisthrelilleresueckmailin.
bran.
en.
n.
enononn.
can.
stziy.
ala.
esa.
eistthynte.
mezy.
mincon.
deele.
llen.
eareerohor.
a.
gh.
te.
setiahiololakrh.
h.
zhard.
blaityaeazaryresok.
oghabrron.
h.
xicaderivelellly.
kaday.
mignnyondriaman.
kaiondos.


In [28]:
loss=0.0
for w in words[:3]:
    chs=["."]+list(w)+ ["."]
    for ch1,ch2 in zip(chs,chs[1:]):
        idx1=stoi[ch1]
        idx2=stoi[ch2]
        prob = P[idx1,idx2]
        logitprob= torch.log(prob)
        nll = -logitprob
        loss += nll
        print(f"{ch1}{ch2}: {prob:.4f}  {nll:.4f}")
print(f"{loss}")

.e: 0.0478  3.0408
em: 0.0377  3.2793
mm: 0.0253  3.6772
ma: 0.3899  0.9418
a.: 0.1960  1.6299
.o: 0.0123  4.3982
ol: 0.0780  2.5508
li: 0.1777  1.7278
iv: 0.0152  4.1867
vi: 0.3541  1.0383
ia: 0.1381  1.9796
a.: 0.1960  1.6299
.a: 0.1377  1.9829
av: 0.0246  3.7045
va: 0.2495  1.3882
a.: 0.1960  1.6299
38.78563690185547


In [50]:
xs=[]
ys=[]
for w in words[:1]:
    chs=["."]+list(w)+ ["."]
    for ch1,ch2 in zip(chs,chs[1:]):
        idx1=stoi[ch1]
        idx2=stoi[ch2]
        xs.append(idx1)
        ys.append(idx2)
xs=torch.tensor(xs)
ys=torch.tensor(ys)

In [59]:
xs

tensor([ 0,  5, 13, 13,  1])

In [60]:
ys

tensor([ 5, 13, 13,  1,  0])

In [61]:
import torch.nn.functional as F
X=F.one_hot(xs,num_classes=27).float()
Y=F.one_hot(ys,num_classes=27).float()

In [62]:
W=torch.randn(27,27)
logit= X@W
expit= torch.exp(logit) 
prob= expit/expit.sum(1,keepdims=True)
prob


tensor([[0.0123, 0.0279, 0.0083, 0.0335, 0.0096, 0.0400, 0.0015, 0.0097, 0.1375,
         0.0432, 0.0389, 0.0594, 0.0074, 0.0275, 0.0260, 0.0071, 0.0247, 0.0157,
         0.0219, 0.0183, 0.0184, 0.0446, 0.0297, 0.1463, 0.1385, 0.0139, 0.0381],
        [0.0305, 0.0123, 0.0761, 0.0534, 0.0195, 0.0102, 0.0248, 0.0613, 0.0183,
         0.0732, 0.0160, 0.0313, 0.0126, 0.0447, 0.0459, 0.0595, 0.1344, 0.0072,
         0.0459, 0.0496, 0.0354, 0.0678, 0.0095, 0.0362, 0.0115, 0.0102, 0.0028],
        [0.0793, 0.0461, 0.0324, 0.0453, 0.0797, 0.0090, 0.0898, 0.0682, 0.0143,
         0.0391, 0.0421, 0.0048, 0.0191, 0.0533, 0.0144, 0.0276, 0.0451, 0.0233,
         0.0439, 0.0097, 0.0099, 0.0253, 0.0266, 0.0297, 0.0544, 0.0387, 0.0292],
        [0.0793, 0.0461, 0.0324, 0.0453, 0.0797, 0.0090, 0.0898, 0.0682, 0.0143,
         0.0391, 0.0421, 0.0048, 0.0191, 0.0533, 0.0144, 0.0276, 0.0451, 0.0233,
         0.0439, 0.0097, 0.0099, 0.0253, 0.0266, 0.0297, 0.0544, 0.0387, 0.0292],
        [0.0339, 0.0087,